//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbovSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public string start { get; set; }
        public string finish { get; set; }
        public string Description { get; set; }
        public string position { get; set; }
        public string responsibilities { get; set; }
        public int workplaceID { get; set; }
    
        public virtual Workplace Workplace { get; set; }
    }
}
