//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbovSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public string degree { get; set; }
        public string start { get; set; }
        public string finish { get; set; }
        public string certificate { get; set; }
    }
}
