//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbovSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workplace
    {
        public Workplace()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int id { get; set; }
        public string company { get; set; }
        public string start { get; set; }
        public string finish { get; set; }
        public string position { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
